# Generated by Django 2.2.15 on 2020-08-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(default='education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='interests',
            field=models.TextField(default='interests'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_experience',
            field=models.TextField(default='work'),
        ),
    ]
