# Generated by Django 2.2.15 on 2020-08-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_public_cv'),
        ('blog', '0003_auto_20200822_1156'),
    ]

    operations = [
    ]
